### PR TITLE
Revert menu_main_home.png to menu_main_sortie.png

### PR DESCRIPTION
**Pull request by n0k0m3**
2fa417e857efe38e4e5e3e28ebc9ba5c5e3c3066
menu_main_home.png => stopped the combat script before night battle => cannot find homepage => Script stop
=> Revert changes

### CODE REVIEW

**Comment by mrmin123** [comment]
Wait so what's happening? The script stops battle before night battle (is this intended?) and then it can't find `menu_main_home.png` even though it's at home?

**Comment by n0k0m3** [comment]
Idk what happened exactly but it seemed there are some portions of the night battle confirmation looks the same as menu_main_home.png and the script determined that the current screen is homepage and looks for menu_main_sortie.png and cannot find it => 10 appfocus => Script exit :/

Edit: Gonna do some debug run

**Comment by mrmin123** [comment]
Gotcha. Ok. The only reason I made it `menu_main_home.png` was because of the possibility of the mouse hovering over `menu_main_sortie.png`. Could you add the line

```
rejigger_mouse(self.kc_window, 370, 770, 100, 400)
```

BEFORE the reverted line and update the PR'ed branch?

**Comment by n0k0m3** [comment]
Testing...

**Comment by n0k0m3** [comment]
Tried to put all rejigger_mouse after all sortie end event but it seemed none of them can solve the problem completely.
Gonna close this PR branch and test b4 resubmit again

**Comment by mrmin123** [comment]
I'll take another look at it later tonight, as well, if it's not resolved by then.

**Pull request closed without merging**
