### PR TITLE
47 catbomb

### PR DESCRIPTION
**Pull request by perryhuynh**

### CODE REVIEW

**Comment by kevin01523** [comment]
ah my mistake did not notice that one.

**Comment by mrmin123** [comment]
The returned_fleet check is still there in the master version.

@perryhuynh I tested your PR and with 0.9 the line_abreast formation would be selected when line_ahead was specified in the config. 0.95 rectified the problem. Could you re-test with 0.95 and/or exact and update your PR if they work?

**Comment by perryhuynh** [comment]
Yeah, I will test it on 3-2 and then do another PR

**Comment by perryhuynh** [comment]
PR updated

**Pull request merged**
