### PR TITLE
Adding SSVs to sub switching

### PR DESCRIPTION
**Pull request by waicool20**
Due to recent farming efforts I've finally gotten Shioi :3 wanted to send her to orel duty immediately, and to my surprise she isn't in the sub switching list...

### CODE REVIEW

**Comment by waicool20** [comment]
And also got to get Hitomi and Iyo on the list too :p

**Comment by mrmin123** [comment]
Exclusion of SSVs was a deliberate decision (see #234 and #182), but I'm not against the ability of giving users the ability to forcibly include them in the switch sub module. I think with this implementation it'll still keep SSVs out of the rotation even if `all` is selected, which is desired at this point.

That said, could you update the image so that it conforms to the other `fleetcomp_shiplist_submarine*.png` images? Dimensions and location of text and such.

**Comment by waicool20** [comment]
I see, how about including images for Kai as well, and options eg. 'i-8_kai'.
The only thing we need to do is add more images for them(add name with Kai), since atm i see you're filtering Kaid SS by leaving some space besides the name.

So in other words add images without the blank space on the right of the name, and name it *_kai.png, if the user enables the Kai variant of the SS then it also enables the base form.

**Comment by waicool20** [comment]
This seems to work well having a separate kai image, the script is able to choose kai and non-kai variants if the kai image is enabled. I also had to bump up the similarity from 0.9 to 0.95, since I also noticed I-58/I-401 getting mistaken for I-8, so basically same problem as #288. Sadly I couldn't add other subs kai images because I don't have them on hand yet :/ ( Nimu where are you :C )

**Comment by mrmin123** [comment]
Having the separate kai images is a good way to implement this. One thing is that the text isn't aligned to the right edge of the text, but on the left edge, so for I-8-kai the image should be shifted to the right. The exclusion isn't done by leaving space to the right of the sub's name, but by the ship's class name (text on the left).

**Comment by mrmin123** [comment]
I can also add the images for the other SSVs so no worries on that end.

**Comment by mrmin123** [comment]
Merging in and continuing work in #303. Thanks for the PR!

**Pull request merged**
