### PR TITLE
Adding luigi support for sub switch module

### PR DESCRIPTION
**Pull request by waicool20**
Because Luigi needs to experience the joy of Orel Cruising first hand

### CODE REVIEW

**Comment by mrmin123** [comment]
Cool. Could you re-create the image asset following the [guidelines](https://github.com/mrmin123/kancolle-auto/wiki/Asset-generation-guide#submarine-switch-assets)? Thanks.

**Comment by waicool20** [comment]
Her name is gonna get cut off, is that fine?

**Comment by mrmin123** [comment]
Oh is her name longer than the current width limit? Hmm. It might be better to cut off the name tho, since the left padding is to make sure that the sub isn't in a fleet already, so yea, lets do that.

**Comment by waicool20** [comment]
Ok that should do it, poor luigi :( her name is too long lol

**Comment by mrmin123** [comment]
Merged, thanks!

**Pull request merged**
