### PR TITLE
Fall 2016 event images

### PR DESCRIPTION
**Pull request by dice4321**

### CODE REVIEW

**Review by dice4321 — COMMENTED** [review]
Updated submarine pictures

**Comment by mrmin123** [comment]
I've not tested this, but I'll take your word that it's working. Thanks for the PR!

**Comment by dice4321** [comment]
I've tested the first map using the images from wikia and it worked. So if logic follows, the other should work as well. I underestimated how large the medals would cover the stars so I'll redo them just in case. Man, I feel relieved to see you back.

**Comment by mrmin123** [comment]
The things to consider are the medals, the progress bar, the LBAS symbol, and any buttons that show up to switch pages. It actually leads to a surprisingly small amount of space to work with, but thanks for the updates! Historically I didn't use the images from wikia/wiki due to fear of compression leading to mismatches, but I guess it's ok to use now.

And thanks, it's good to be back... although I'm not looking forward to taking on another event lol

**Pull request merged**
