### PR TITLE
Updated several pre-sortie check images

### PR DESCRIPTION
**Pull request by waicool20**

### CODE REVIEW

**Comment by waicool20** [comment]
Fixes #353

**Comment by mrmin123** [comment]
@waicool20 this is confirmed working?

**Comment by waicool20** [comment]
Yeah I've tested it it's fine, but your welcome to keep the issue open to let people test it.

**Comment by mrmin123** [comment]
Nah it's just that I won't have a chance to test any time soon... thanks for the PR!

**Pull request merged**
